FROM nvidia/cuda:12.1.0-devel-ubuntu18.04

# Install ROS
RUN apt-get update && apt-get install -y lsb-release curl 
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y ros-melodic-desktop
RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

# Install OpenCV
WORKDIR /home/Downloads
RUN sudo apt-get update && apt install -y cmake g++ wget unzip
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip && unzip opencv.zip
RUN wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.x.zip && unzip opencv_contrib.zip
RUN mkdir -p build && cd build && \
    cmake \
        -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.x/modules \
        -DCMAKE_BUILD_TYPE=RELEASE \
        -DOPENCV_PYTHON3_VERSION=OFF \
        # -DCMAKE_CXX_STANDARD=17 \
        ../opencv-4.x && \
    make -j6 && \
    sudo make install .

# Install VTK
RUN sudo apt-get update && apt-get install -y libxt-dev git
RUN wget -O vtk.zip https://www.vtk.org/files/release/8.2/VTK-8.2.0.zip && unzip vtk.zip
RUN cd VTK-8.2.0 && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD=17 .. && \
    make -j6 && \
    sudo make install .

# Install PCL
RUN sudo apt-get update && apt-get install libeigen3-dev libflann-dev
RUN wget -O pcl.zip https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.13.0/source.zip && unzip pcl.zip
RUN cd pcl && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_STANDARD=17 .. && \
    make -j6 && \
    sudo make install .

RUN sudo apt install libyaml-cpp-dev

RUN apt-get update && apt-get install -y 
    ros-melodic-pcl-ros
WORKDIR /
